version: "3.9"

volumes:
  postgres_data_1:
  postgres_data_2:

services:
  postgres1:
    image: postgres:15
    volumes:
      - postgres_data_1:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=nogueira-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  postgres2:
    image: postgres:15
    volumes:
      - postgres_data_2:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=melancia
      - POSTGRES_USER=banana
      - POSTGRES_PASSWORD=arroz
    ports:
      - 5433:5432
